[Task][69807] Init API
awesome-academy/FoodMenu pull request #3
Opened 2023-10-06 09:26 UTC by bachnd2k1

## [Task][69807] Init API

### [Redmine link]
https://edu-redmine.sun-asterisk.vn/issues/69807

#### Screenshots (nếu có)

![Screen Shot 2023-10-06 at 16 26 10](https://github.com/awesome-academy/FoodMenu/assets/75248050/0f1c179e-96e8-49da-965f-eb2c4e7602e8)

2023-10-09 02:03 UTC, hlinh88 commented on FoodMenu/FoodMenu/Scene/Home/HomeViewController.swift
> +    var chefsSpecials:[Food] = []
coding convention

2023-10-09 02:03 UTC, hlinh88 commented on FoodMenu/FoodMenu/Scene/Home/HomeViewController.swift
> +        }
tách ra folder chứ sao gọi thẳng trong ViewController như này :v

2023-10-10 02:58 UTC, hlinh88 commented on FoodMenu/FoodMenu/Model/Endpoint.swift
> +}
Viết lại thành Struct Endpoints

2023-10-10 02:58 UTC, hlinh88 commented on FoodMenu/FoodMenu/Scene/Home/View/HomeViewController.swift
> +        print("foodCategory+\(self.foodCategory)")
không đẩy print

2023-10-10 02:58 UTC, hlinh88 commented on FoodMenu/FoodMenu/Scene/TabBar/TabBarController.swift
> +        let homeVC = UINavigationController.setUpHomeController()
đẩy setup sub-viewcontroller qua app navigator

2023-10-10 03:19 UTC, hlinh88 commented on FoodMenu/FoodMenu/Model/Endpoint.swift
> +    }
pass parameter không pass thẳng vào url

2023-10-10 03:19 UTC, hlinh88 commented on FoodMenu/FoodMenu/Scene/App/AppNavigator.swift
> +        tabBar.tabBar.barTintColor = .white
customize không nhất thiết phải ở AppNavigator

2023-10-10 03:29 UTC, hlinh88 requested changes

2023-10-10 03:29 UTC, hlinh88 commented on FoodMenu/FoodMenu/Model/Endpoint.swift
> +    }
tham khảo https://github.com/awesome-academy/Structure_IOS/blob/mvvm_architect/src/Structure_IOS/Utils/URLs.swift

2023-10-10 03:29 UTC, hlinh88 commented on FoodMenu/FoodMenu/Scene/App/AppNavigator.swift
> +        tabBar.tabBar.barTintColor = .white
chưa fix comment

2023-10-10 03:43 UTC, hlinh88 approved these changes

2023-10-10 04:08 UTC, tuta-3205 commented on FoodMenu/FoodMenu/Scene/App/AppNavigator.swift
> +//        tabBar.setViewControllers([homeVC, favouriteVC], animated: true)
code này k dùng thì xóa hi, còn nếu còn dùng thì cmt TODO: implement when ....

2023-10-10 04:08 UTC, tuta-3205 commented on FoodMenu/Podfile.lock
> +  - Reusable/View (4.1.1)
file này cũng ignore hi

2023-10-10 04:40 UTC, tuta-3205 approved these changes

2023-10-10 04:40 UTC, merged